source 'https://rubygems.org'
ruby '2.2.1'

gem "calabash-cucumber", ">= 0.17.0", "< 2.0"
gem 'activerecord', '4.2.5'
gem 'faker', '1.6.1'
gem 'httparty', '0.13.7'
gem 'm', '~> 1.4.0'
gem 'minitest-reporters', '1.1.5'
gem 'minitest', '5.8.3'